### ISSUE TITLE
Finish draft of paper

### ISSUE THREAD

**Issue by wjladams** [wjladams/ahpNewPriority#1]
This paper is the first draft write up of the idea.  Here are links to the relevant docs in this github repo.
- [Link To TeX](https://github.com/wjladams/ahpNewPriority/blob/master/notes/EigenVersionDraft1.tex)
- [Link To PDF](https://github.com/wjladams/ahpNewPriority/blob/master/notes/EigenVersionDraft1.pdf)

**Comment by wjladams** [comment]
@erokou Hey, look at that, I assign things to myself too :)

**Comment by erokou** [comment]
shall I guess that you would like me to add here some short review paragraph? from my review thing?

**Comment by wjladams** [comment]
@erokou I like your spunk, but the https://github.com/wjladams/priorities-zoo is the place where I put all the work around the review.  I'm keeping them as 2 separate projects, although if you prefer me to merge them together, just let me know.
